#!/bin/bash


divide() {
local num1 num2
    
    echo "First Number is:"
    read num1
    echo "Second Number is:"
    read num2

    echo "Debug: num1=$num1 num2=$num2"

if [ $num2 -eq "0" ]; then
    echo "Error: Division by Zero is irrational."
    exit 1
fi

result=$((num1 / num2))

echo "Num1 is $num1 and Num2 is $num2"

echo "the result is :$result"
}

divide