#!/bin/bash



divide() {
local num1 num2

    echo "First Number is:"
    read num1
    echo "Second Number is:"
    read num2

if [ $num2 -eq "0" ]; then
    echo "Error: Division by Zero is irrational."
    exit 1
fi

result=$((num1 / num2))

echo "Num1 is $num1 and Num2 is $num2"

echo "the result is :$result"
}

command_check() {
    local cmd
    echo "Check command:"
    read cmd
    command -v $cmd 2>/dev/null

    if [[ $? -ne 0 ]]; then
    echo "Command doesn't exist"
    exit 1
    else
    echo "Command exists"
    fi
}
command_check
